### PR TITLE
Add .minttyrc for mintty support

### PR DESCRIPTION
**Pull request by bobcats**

### CODE REVIEW

**Comment by whatyouhide** [comment]
Hey there, thanks for contributing. I'd be happy to merge this PR in, but I need a few things first:

- Installation instructions for mintty added to the README (in the same format of all the other installation instructions in the README)
- A screenshot added to the PR so that I can have a quick look at the outcome of your additions

:heart:

**Comment by bobcats** [comment]
Sounds good! on it :)

**Comment by bobcats** [comment]
203b9777cd89fb312d64ce0cd64c83df

Shamelessly stolen from the termite config.

**Comment by whatyouhide** [comment]
The screenshot is good to go. One last thing: you added installation instructions in the README right inside the PyCharm section :). If you move that *right before* the "Emacs" section, we'll be good to merge!

**Comment by bobcats** [comment]
Ah, sorry! Should be good to go now.

**Comment by whatyouhide** [comment]
Perfect, thanks for contributing! :smile:

**Pull request merged**
